apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: ssh
    port: {{ .Values.service.ssh.port }}
    protocol: TCP
    targetPort: {{ .Values.service.http.port }}
  - name: https
    port: {{ .Values.service.https.port }}
    protocol: TCP
    targetPort: {{ .Values.service.https.port }}
  - name: http
    port: {{ .Values.service.http.port }}
    protocol: TCP
    targetPort: {{ .Values.service.http.port }}
  selector:
    app.kubernetes.io/name: {{ include "gitlab.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
