replicaCount: 1

image:
  repository: rocker/rstudio
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8787

ingress:
  ip: 34.244.95.29
  enabled: true
  annotations: {}
  
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
