apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  {{ template "rstudio.fullname" . }}
  namespace: rstudio
spec:
  rules:
  - host: rstudio.34.244.95.29.nip.io
    http:
      paths:
      - backend:
          serviceName: {{ include "rstudio.fullname" . }}
          servicePort: 8787
