apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  {{ template "rstudio.fullname" . }}
  namespace: rstudio
spec:
  rules:
  - host: {{ .Values.ingress.hosts.host }}
    http:
      paths:
      - backend:
          serviceName: {{ include "rstudio.fullname" . }}
          servicePort: 8787