kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "rstudio.fullname" . }}
  namespace: rstudio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
  volumeMode: Filesystem