apiVersion: v1
kind: Service
metadata:
  name: {{ include "rstudio.fullname" . }}
  namespace: rstudio
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port:  {{ .Values.service.port }}
    targetPort:  {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "rstudio.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}